mklink "%HOME%\vimfiles\vimrc" "%HOME%\dotfiles\.vimrc"
mklink "%HOME%\vimfiles\gvimrc" "%HOME%\dotfiles\gvimrc"
mklink "%HOME%\.bashrc" "%HOME%\dotfiles\.bashrc"
mklink "%HOME%\.tmux.conf" "%HOME%\dotfiles\.tmux.conf" 
rem mklink /d "%HOME%\.config" "%HOME%\dotfiles\.config" 
rem mklink /D %HOMEPATH%"\.vim\ftdetect" %HOMEPATH%"\dotfiles\ftdetect"
rem mklink /D %HOMEPATH%"\.vim\indent" %HOMEPATH%"\dotfiles\indent"
rem mklink /D %HOMEPATH%"\.vim\colors" %HOMEPATH%"\dotfiles\colors"
