#!/bin/bash
install_docker() {
  # ref https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04-ja

  # remove old version docker
  sudo apt remove docker docker-engine docker.io containerd runc
  
  sudo apt update
  sudo apt install apt-transport-https ca-certificates curl software-properties-common
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  sudo apt update

  # check policy
  # checked getting Docker repository (ubuntu focal stable
  # apt-cache policy docker-ce

  sudo apt install docker-ce

  # check running docker
  sudo systemctl status docker
}
